### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by MaryBethBaker** [canada-ca/PCTF-CCP#1]
Hey @trbouma,

Any chance you can make the repo name easier for people understand who searching github for cool projects?

What about:
* CdnTrustFramework
*CanTrustFramework
*CdnTrustFrmwk

Thanks!
Mary Beth Baker

**Comment by trbouma** [comment]
The acronym we are using is PCTF so I want to keep it short for now. I presume we can change it later. This is experimental for now.

**Comment by MaryBethBaker** [comment]
Hi Tim,

Can you make or provide the name in the read.md in French too?

Thanks,
Mary Beth Baker

**Comment by trbouma** [comment]
repo name now has French acronym
